name: Validate Bicep Files
permissions:
  id-token: write

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.bicep'
      - '**/*.bicepparam'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"

  validate-bicep:
    name: Validate Bicep Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep Parameters Files
        run: |
          echo "Validating Bicep parameters files..."
          find ./.bicep -name "*.bicepparam" -exec az bicep build-params -f {} \;

      - name: Validate Bicep Files
        run: |
          echo "Validating Bicep files..."
          az bicep build -f .bicep/main.bicep;

      - name: Publish Bicep Artifacts
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: ARM-template
          path: |
            .bicep/*.json