name: Validate Bicep Files
permissions:
  id-token: write

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.bicep'
      - '**/*.bicepparam'

jobs:
  validate-bicep:
    name: Validate Bicep Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate Bicep Parameters Files
        run: |
          echo "Validating Bicep parameters files..."
          ls
          cd .bicep
          ls
          find . -name "*.bicepparam" -exec az bicep build-params -f {} \;
          find . -name "*.bicepparam"

      - name: Validate Bicep Files
        run: |
          echo "Validating Bicep files..."
          ls
          cd .bicep
          ls
          find . -name "*.bicep" -exec az bicep build -f {} \;
          find . -name "*.bicep"

      - name: Publish Bicep Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ARM-template
          path: |
            **/*.json
            !**/bin/**
            !**/obj/**