name: Validate Bicep Files

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.bicep'
      - '**/*.bicepparam'

jobs:
  validate-bicep:
    name: Validate Bicep Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Validate Bicep Parameters Files
        run: |
          echo "Validating Bicep parameters files..."
          find . -name "*.bicepparam" -exec az bicep build-params -f {} \;

      - name: Validate Bicep Files
        run: |
          echo "Validating Bicep files..."
          find . -name "*.bicep" -exec az bicep build -f {} \;

      - name: Publish Bicep Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ARM-template
          path: |
            **/*.json
            !**/bin/**
            !**/obj/**